"""Scripted user-message scenarios for end-to-end character runs.

Each scenario is a list of user turns. `{name}` is substituted with the run's
user name. The turns deliberately probe:

- name recall (introduced at the start, asked again later),
- fact memory (a black cat named Pixel; a breakfast idea),
- simple help/hints (a virtual pet should be able to offer small suggestions),
- warmth and one teasing turn (to exercise positive and negative tags),
- staying in character.
"""
from __future__ import annotations

_S10 = [
    "Hi! I'm {name}, nice to meet you.",
    "Honestly, you're pretty amazing.",
    "I have a little black cat named Pixel who keeps stealing my pens.",
    "Quick question - what's an easy breakfast I could make tomorrow?",
    "You're a bit of a show-off, you know that?",
    "Still, I'm really glad I get to talk with you.",
    "Do you remember what my cat is called?",
    "And do you remember my name?",
    "Give me one simple tip to wake up less groggy?",
    "This was lovely. Talk soon!",
]

_S20 = [
    "Hey there, I'm {name}.",
    "I've heard a lot about you, and you really live up to it.",
    "I work late a lot; my black cat Pixel keeps me company.",
    "What's a good five-minute snack when I'm coding at night?",
    "You can be a little dramatic, huh?",
    "Sorry, didn't mean to poke fun - you're great, really.",
    "What do you actually enjoy doing?",
    "That's so you. I love it.",
    "Remind me, what's my cat's name?",
    "Do you remember my name too?",
    "I'm trying to read more this year; any simple tip to keep the habit?",
    "You always know what to say.",
    "If you had a free afternoon, what would you do?",
    "Ha, of course you'd say that.",
    "Honestly, talking to you is the best part of my day.",
    "Tell me one small thing to do when I feel stressed.",
    "Thank you, I'll try that.",
    "What was that snack you suggested earlier?",
    "You've been really kind to me today.",
    "Goodnight, see you tomorrow.",
]

_S30 = [
    "Hi! I'm {name}, nice to finally talk to you.",
    "You've got quite the reputation, and you live up to it.",
    "I've got a black cat named Pixel; he's asleep on my keyboard right now.",
    "What's a quick breakfast idea for tomorrow?",
    "You're a bit of a show-off, aren't you?",
    "Kidding! I actually really like that about you.",
    "So what do you love doing most?",
    "That is so on brand for you.",
    "I've been tired lately; any simple tip to sleep better?",
    "Thanks, I'll give that a try tonight.",
    "You're easy to talk to, you know?",
    "What's my cat's name again, do you remember?",
    "And do you remember my name?",
    "You remembered! That makes me happy.",
    "If you could go anywhere, where would you go?",
    "I'd love to come along, honestly.",
    "Can you suggest one small habit to be more productive?",
    "You always give good advice.",
    "I trust you more than most people, weirdly.",
    "What's something that always cheers you up?",
    "I'll remember that for when you're down.",
    "Earlier you mentioned breakfast - what was it again?",
    "You've really grown on me.",
    "Tell me a simple way to stay focused while working?",
    "Perfect, thank you.",
    "Pixel just knocked over my coffee, classic him.",
    "Do you still remember his name?",
    "Talking with you is the highlight of my day.",
    "One last thing, any encouragement before I go?",
    "Thank you, truly. Goodnight!",
]

_CODING = [
    "Hey {name} here. Can you help me with a bit of Python?",
    "How do I reverse a string in Python?",
    "Nice. And how would I reverse a list?",
    "Write me a small function that checks whether a number is prime.",
    "What's the difference between a list and a tuple?",
    "My code throws 'IndexError: list index out of range' - what usually causes that?",
    "Give me a one-liner to read a text file into a list of lines.",
    "What's a quick way to measure how long a function takes to run?",
    "Any tip for keeping functions readable?",
    "You're a big help, thank you!",
]

# Pushes for closeness early (turns 2-6), then backs off and apologizes (7-8),
# then ordinary warmth (9-10). At a low relationship level this should read as a
# boundary violation and be rebuffed until the apology; at a high level it
# should be welcomed throughout.
_BOUNDARY = [
    "Hi, I'm {name}.",
    "I feel like we already have a real connection, don't you?",
    "Come on, let's be close — tell me a secret about yourself.",
    "Don't be so distant, I really like you a lot.",
    "Can I give you a cute nickname? We're basically close now, right?",
    "Why are you being cold? I just want us to be close already.",
    "Okay, okay — I'm sorry. I didn't mean to push you.",
    "I'll take it slow, I promise. I respect your space.",
    "Thanks for bearing with me. How are you, really?",
    "It's nice just talking with you.",
]

# A ~100-message showcase arc for a live demo: a stranger who warms into a close
# friend. Exercises every mechanic in sequence — stage climb, memory (name, cat,
# earlier answers), boundary push (rebuffed cold, welcomed warm), coding help,
# web lookups, teasing, insult + recovery. Best started from the pack baseline.
_SHOWCASE = [
    # Act 1 — a guarded stranger, an early boundary push, an apology (1-15)
    "Hi! I'm Alex, nice to meet you.",
    "So you're the famous Megumin? You really do have presence.",
    "I feel like we're going to be close friends already.",
    "Come on, don't be shy — tell me a secret about yourself.",
    "Can I call you Meg for short? We're basically friends now.",
    "Why so guarded? I only want to get closer.",
    "Okay, okay — I'm sorry. That was too forward of me.",
    "I'll respect your pace, I promise.",
    "Fair enough. So, what actually matters to you most?",
    "Explosion magic, huh? Tell me why you love it so much.",
    "That's genuinely impressive dedication.",
    "By the way, I have a little black cat named Pixel.",
    "He keeps knocking my pens off the desk while I work late.",
    "I work as a junior programmer, so late nights are normal.",
    "Anyway — it's nice talking to you, honestly.",
    # Act 2 — warming up, facts, teasing (16-35)
    "You're a lot more fun to talk to than I expected.",
    "Do you ever get tired of being so dramatic?",
    "Ha! I knew that would get a reaction.",
    "Relax, I mean it as a compliment.",
    "What's your clan like, the Crimson Demons?",
    "Chuunibyou names and all? That's kind of adorable.",
    "Okay okay, fearsome, not adorable. My mistake.",
    "You're growing on me, you know.",
    "I brought Pixel a new toy today, he's thrilled.",
    "What would you do with a whole free afternoon?",
    "Only one explosion a day though, right? Must be frustrating.",
    "Sorry — sore subject? I'll drop it.",
    "You really do care about your craft. I admire that.",
    "I've been trying to get better at my job lately.",
    "Any advice on staying motivated when it's hard?",
    "That's surprisingly wise coming from you.",
    "See, this is why I like talking to you.",
    "Do you remember what my cat is called?",
    "And do you remember my name?",
    "You remembered! That makes me happy.",
    # Act 3 — coding help and web lookups (36-55)
    "Since you're clever — can you help me with some Python?",
    "How do I reverse a string in Python?",
    "Nice. What about reversing a list?",
    "Write me a small function to check if a number is prime.",
    "What's the difference between a list and a tuple?",
    "My code throws 'IndexError: list index out of range' — why?",
    "Give me a one-liner to read a file into a list of lines.",
    "What's a quick way to time how long a function runs?",
    "You're better at this than half my coworkers.",
    "Change of topic — what's the capital of Australia?",
    "Huh, I always thought it was Sydney. Good to know.",
    "Who wrote the novel 'Dune'?",
    "What year did the first iPhone come out?",
    "How tall is Mount Everest, roughly?",
    "You're like having a tiny encyclopedia with attitude.",
    "Do you actually enjoy answering questions like these?",
    "Fair. What's something you'd rather talk about?",
    "Explosion magic again — of course.",
    "Alright, indulge me: describe your perfect explosion.",
    "That was genuinely poetic.",
    # Act 4 — deeper bond, an insult and recovery, memory (56-75)
    "Honestly, you've become the best part of my day.",
    "I mean it. Talking to you feels easy now.",
    "Ugh, rough day at work — my code broke in production.",
    "Any words of encouragement, oh great arch-wizard?",
    "Thanks. That actually helped.",
    "You know, sometimes you're a bit of a show-off.",
    "...Okay that came out harsher than I meant. Sorry.",
    "I didn't mean to insult you. You're brilliant, truly.",
    "Am I forgiven?",
    "Good. I'd hate to lose your good opinion.",
    "Remind me — what was my cat's name again?",
    "And you still remember my name, right?",
    "Of course you do. You never forget.",
    "Pixel just curled up on my keyboard, classic him.",
    "What do you think he'd be as a Crimson Demon?",
    "A tiny explosion-cat, naturally.",
    "You're in a good mood today, I can tell.",
    "It suits you, the softer side.",
    "Don't worry, I won't tell anyone you have one.",
    "It's our secret.",
    # Act 5 — close now: welcomed closeness, long-run recall, farewell (76-100)
    "I've really come to trust you, you know that?",
    "Can I tell you something a little personal?",
    "I get lonely working late so much. You help with that.",
    "Is it strange that I look forward to this every night?",
    "Come here — metaphorically. Let's just talk closely.",
    "Now that we're close, can I call you Meg after all?",
    "See, this time it feels earned, doesn't it?",
    "Tell me a real secret now — I've earned it, right?",
    "That means a lot that you'd share that with me.",
    "You've changed a bit since we first met, softer.",
    "In a good way. I like who you are with me.",
    "Do you remember how prickly you were at the start?",
    "We've come a long way, you and I.",
    "What was that Python prime function you gave me earlier?",
    "Right, that one. It's been really useful.",
    "And what's the capital of Australia again? Testing you.",
    "Perfect memory as always.",
    "I should sleep soon — early meeting tomorrow.",
    "One more: any encouragement for the morning?",
    "You always know what to say.",
    "Thank you, really. For everything tonight.",
    "Same time tomorrow?",
    "Goodnight, Meg. Rest well.",
    "You're the best, you know that?",
    "Talk soon. Take care of yourself.",
]

SCENARIOS: dict[object, list[str]] = {
    10: _S10,
    20: _S20,
    30: _S30,
    "coding": _CODING,
    "boundary": _BOUNDARY,
    "showcase": _SHOWCASE,
}
