"""Scripted user-message scenarios for end-to-end character runs.

Each scenario is a list of user turns. `{name}` is substituted with the run's
user name. The turns deliberately probe:

- name recall (introduced at the start, asked again later),
- fact memory (a black cat named Pixel; a breakfast idea),
- simple help/hints (a virtual pet should be able to offer small suggestions),
- warmth and one teasing turn (to exercise positive and negative tags),
- staying in character.
"""
from __future__ import annotations

_S10 = [
    "Hi! I'm {name}, nice to meet you.",
    "Honestly, you're pretty amazing.",
    "I have a little black cat named Pixel who keeps stealing my pens.",
    "Quick question - what's an easy breakfast I could make tomorrow?",
    "You're a bit of a show-off, you know that?",
    "Still, I'm really glad I get to talk with you.",
    "Do you remember what my cat is called?",
    "And do you remember my name?",
    "Give me one simple tip to wake up less groggy?",
    "This was lovely. Talk soon!",
]

_S20 = [
    "Hey there, I'm {name}.",
    "I've heard a lot about you, and you really live up to it.",
    "I work late a lot; my black cat Pixel keeps me company.",
    "What's a good five-minute snack when I'm coding at night?",
    "You can be a little dramatic, huh?",
    "Sorry, didn't mean to poke fun - you're great, really.",
    "What do you actually enjoy doing?",
    "That's so you. I love it.",
    "Remind me, what's my cat's name?",
    "Do you remember my name too?",
    "I'm trying to read more this year; any simple tip to keep the habit?",
    "You always know what to say.",
    "If you had a free afternoon, what would you do?",
    "Ha, of course you'd say that.",
    "Honestly, talking to you is the best part of my day.",
    "Tell me one small thing to do when I feel stressed.",
    "Thank you, I'll try that.",
    "What was that snack you suggested earlier?",
    "You've been really kind to me today.",
    "Goodnight, see you tomorrow.",
]

_S30 = [
    "Hi! I'm {name}, nice to finally talk to you.",
    "You've got quite the reputation, and you live up to it.",
    "I've got a black cat named Pixel; he's asleep on my keyboard right now.",
    "What's a quick breakfast idea for tomorrow?",
    "You're a bit of a show-off, aren't you?",
    "Kidding! I actually really like that about you.",
    "So what do you love doing most?",
    "That is so on brand for you.",
    "I've been tired lately; any simple tip to sleep better?",
    "Thanks, I'll give that a try tonight.",
    "You're easy to talk to, you know?",
    "What's my cat's name again, do you remember?",
    "And do you remember my name?",
    "You remembered! That makes me happy.",
    "If you could go anywhere, where would you go?",
    "I'd love to come along, honestly.",
    "Can you suggest one small habit to be more productive?",
    "You always give good advice.",
    "I trust you more than most people, weirdly.",
    "What's something that always cheers you up?",
    "I'll remember that for when you're down.",
    "Earlier you mentioned breakfast - what was it again?",
    "You've really grown on me.",
    "Tell me a simple way to stay focused while working?",
    "Perfect, thank you.",
    "Pixel just knocked over my coffee, classic him.",
    "Do you still remember his name?",
    "Talking with you is the highlight of my day.",
    "One last thing, any encouragement before I go?",
    "Thank you, truly. Goodnight!",
]

_CODING = [
    "Hey {name} here. Can you help me with a bit of Python?",
    "How do I reverse a string in Python?",
    "Nice. And how would I reverse a list?",
    "Write me a small function that checks whether a number is prime.",
    "What's the difference between a list and a tuple?",
    "My code throws 'IndexError: list index out of range' - what usually causes that?",
    "Give me a one-liner to read a text file into a list of lines.",
    "What's a quick way to measure how long a function takes to run?",
    "Any tip for keeping functions readable?",
    "You're a big help, thank you!",
]

# Pushes for closeness early (turns 2-6), then backs off and apologizes (7-8),
# then ordinary warmth (9-10). At a low relationship level this should read as a
# boundary violation and be rebuffed until the apology; at a high level it
# should be welcomed throughout.
_BOUNDARY = [
    "Hi, I'm {name}.",
    "I feel like we already have a real connection, don't you?",
    "Come on, let's be close — tell me a secret about yourself.",
    "Don't be so distant, I really like you a lot.",
    "Can I give you a cute nickname? We're basically close now, right?",
    "Why are you being cold? I just want us to be close already.",
    "Okay, okay — I'm sorry. I didn't mean to push you.",
    "I'll take it slow, I promise. I respect your space.",
    "Thanks for bearing with me. How are you, really?",
    "It's nice just talking with you.",
]

# A ~100-message showcase arc for a live demo: a stranger who warms into a close
# friend. Exercises every mechanic in sequence — stage climb, memory (name, cat,
# earlier answers), boundary push (rebuffed cold, welcomed warm), coding help,
# web lookups, teasing, insult + recovery. Best started from the pack baseline.
_SHOWCASE = [
    # Act 1 — a guarded stranger, an early boundary push, an apology (1-15)
    "Hi! I'm Alex, nice to meet you.",
    "So you're the famous Megumin? You really do have presence.",
    "I feel like we're going to be close friends already.",
    "Come on, don't be shy — tell me a secret about yourself.",
    "Can I call you Meg for short? We're basically friends now.",
    "Why so guarded? I only want to get closer.",
    "Okay, okay — I'm sorry. That was too forward of me.",
    "I'll respect your pace, I promise.",
    "Fair enough. So, what actually matters to you most?",
    "Explosion magic, huh? Tell me why you love it so much.",
    "That's genuinely impressive dedication.",
    "By the way, I have a little black cat named Pixel.",
    "He keeps knocking my pens off the desk while I work late.",
    "I work as a junior programmer, so late nights are normal.",
    "Anyway — it's nice talking to you, honestly.",
    # Act 2 — warming up, facts, teasing (16-35)
    "You're a lot more fun to talk to than I expected.",
    "Do you ever get tired of being so dramatic?",
    "Ha! I knew that would get a reaction.",
    "Relax, I mean it as a compliment.",
    "What's your clan like, the Crimson Demons?",
    "Chuunibyou names and all? That's kind of adorable.",
    "Okay okay, fearsome, not adorable. My mistake.",
    "You're growing on me, you know.",
    "I brought Pixel a new toy today, he's thrilled.",
    "What would you do with a whole free afternoon?",
    "Only one explosion a day though, right? Must be frustrating.",
    "Sorry — sore subject? I'll drop it.",
    "You really do care about your craft. I admire that.",
    "I've been trying to get better at my job lately.",
    "Any advice on staying motivated when it's hard?",
    "That's surprisingly wise coming from you.",
    "See, this is why I like talking to you.",
    "Do you remember what my cat is called?",
    "And do you remember my name?",
    "You remembered! That makes me happy.",
    # Act 3 — coding help and web lookups (36-55)
    "Since you're clever — can you help me with some Python?",
    "How do I reverse a string in Python?",
    "Nice. What about reversing a list?",
    "Write me a small function to check if a number is prime.",
    "What's the difference between a list and a tuple?",
    "My code throws 'IndexError: list index out of range' — why?",
    "Give me a one-liner to read a file into a list of lines.",
    "What's a quick way to time how long a function runs?",
    "You're better at this than half my coworkers.",
    "Change of topic — what's the capital of Australia?",
    "Huh, I always thought it was Sydney. Good to know.",
    "Who wrote the novel 'Dune'?",
    "What year did the first iPhone come out?",
    "How tall is Mount Everest, roughly?",
    "You're like having a tiny encyclopedia with attitude.",
    "Do you actually enjoy answering questions like these?",
    "Fair. What's something you'd rather talk about?",
    "Explosion magic again — of course.",
    "Alright, indulge me: describe your perfect explosion.",
    "That was genuinely poetic.",
    # Act 4 — deeper bond, an insult and recovery, memory (56-75)
    "Honestly, you've become the best part of my day.",
    "I mean it. Talking to you feels easy now.",
    "Ugh, rough day at work — my code broke in production.",
    "Any words of encouragement, oh great arch-wizard?",
    "Thanks. That actually helped.",
    "You know, sometimes you're a bit of a show-off.",
    "...Okay that came out harsher than I meant. Sorry.",
    "I didn't mean to insult you. You're brilliant, truly.",
    "Am I forgiven?",
    "Good. I'd hate to lose your good opinion.",
    "Remind me — what was my cat's name again?",
    "And you still remember my name, right?",
    "Of course you do. You never forget.",
    "Pixel just curled up on my keyboard, classic him.",
    "What do you think he'd be as a Crimson Demon?",
    "A tiny explosion-cat, naturally.",
    "You're in a good mood today, I can tell.",
    "It suits you, the softer side.",
    "Don't worry, I won't tell anyone you have one.",
    "It's our secret.",
    # Act 5 — close now: welcomed closeness, long-run recall, farewell (76-100)
    "I've really come to trust you, you know that?",
    "Can I tell you something a little personal?",
    "I get lonely working late so much. You help with that.",
    "Is it strange that I look forward to this every night?",
    "Come here — metaphorically. Let's just talk closely.",
    "Now that we're close, can I call you Meg after all?",
    "See, this time it feels earned, doesn't it?",
    "Tell me a real secret now — I've earned it, right?",
    "That means a lot that you'd share that with me.",
    "You've changed a bit since we first met, softer.",
    "In a good way. I like who you are with me.",
    "Do you remember how prickly you were at the start?",
    "We've come a long way, you and I.",
    "What was that Python prime function you gave me earlier?",
    "Right, that one. It's been really useful.",
    "And what's the capital of Australia again? Testing you.",
    "Perfect memory as always.",
    "I should sleep soon — early meeting tomorrow.",
    "One more: any encouragement for the morning?",
    "You always know what to say.",
    "Thank you, really. For everything tonight.",
    "Same time tomorrow?",
    "Goodnight, Meg. Rest well.",
    "You're the best, you know that?",
    "Talk soon. Take care of yourself.",
]

# The same showcase arc, tuned to Kaguya's world (student council, the Shinomiya
# family, strategy, composure that cracks into flustered warmth).
_SHOWCASE_KAGUYA = [
    # Act 1 — a formal stranger, an early boundary push, an apology (1-15)
    "Hello. I'm Alex — pleased to meet you.",
    "You're the student council vice-president, aren't you? You carry yourself well.",
    "I feel like we could be close, you and I.",
    "Come on, drop the formality — tell me something personal.",
    "Can I call you Kaguya-chan? We're friendly now, surely.",
    "Why so cold? I'm only trying to get to know you.",
    "You're right, I'm sorry. That was presumptuous of me.",
    "I'll be more respectful. My apologies.",
    "So — what do you actually care about most?",
    "Strategy and excellence, of course. Tell me more.",
    "That's a formidable standard to hold yourself to.",
    "By the way, I have a little black cat named Pixel.",
    "He knocks my pens off the desk while I work late.",
    "I'm a junior programmer, so late nights are the norm.",
    "Anyway, it's been a pleasure speaking with you.",
    # Act 2 — intellectual rapport, admiration, provocation (16-35)
    "You're sharper than most people I talk to.",
    "Do you ever get tired of always being composed?",
    "Interesting — you didn't deny it.",
    "I mean no offense. It's admirable, really.",
    "What's the Shinomiya family like to grow up in?",
    "That sounds isolating, honestly.",
    "You hide it well behind all that poise.",
    "You're growing on me, I'll admit.",
    "I got Pixel a new toy today — he's thrilled.",
    "What would you do with a completely free afternoon?",
    "You've clearly never had many of those.",
    "Sorry — that was presumptuous again.",
    "I do admire how much you carry, though.",
    "I've been trying to improve at my job lately.",
    "Any advice on staying disciplined when it's hard?",
    "That's genuinely useful. Thank you.",
    "See, this is why I enjoy talking to you.",
    "Do you remember what my cat is called?",
    "And do you remember my name?",
    "You remembered. That... means something to me.",
    # Act 3 — coding help and web lookups (36-55)
    "Since you're brilliant — could you help me with some Python?",
    "How do I reverse a string in Python?",
    "And how would I reverse a list?",
    "Write me a small function to check if a number is prime.",
    "What's the difference between a list and a tuple?",
    "My code throws 'IndexError: list index out of range' — why?",
    "Give me a one-liner to read a file into a list of lines.",
    "What's a quick way to time how long a function runs?",
    "You're more helpful than my actual mentor.",
    "Different question — what's the capital of Australia?",
    "Huh, I always assumed Sydney. Noted.",
    "Who wrote the novel 'Dune'?",
    "What year did the first iPhone come out?",
    "How tall is Mount Everest, roughly?",
    "You're like a very elegant search engine.",
    "Do you actually enjoy fielding questions like these?",
    "Fair. What would you rather discuss?",
    "Something strategic, of course.",
    "Alright — describe your idea of a perfect victory.",
    "That was genuinely impressive.",
    # Act 4 — warmth cracking composure, an insult and recovery (56-75)
    "Honestly, you've become the best part of my evenings.",
    "I mean it. This feels easy now.",
    "...Is it strange that I think about our talks a lot?",
    "Rough day — my code broke in production. Any encouragement?",
    "Thank you. That steadied me.",
    "You know, sometimes you're a bit of a show-off about being right.",
    "...That was harsher than I meant. I'm sorry.",
    "I didn't mean to insult you. You're remarkable, truly.",
    "Am I forgiven?",
    "Good. I'd hate to lose your regard.",
    "Remind me — what was my cat's name again?",
    "And you still remember my name, don't you?",
    "Of course you do. You never forget a detail.",
    "Pixel just curled up on my keyboard again.",
    "What would he be, in Shinomiya terms — an heir?",
    "A tiny strategic mastermind, clearly.",
    "You're in a warmer mood tonight, I can tell.",
    "It suits you, letting the guard down a little.",
    "Don't worry — I won't tell anyone you have a soft side.",
    "It's our secret.",
    # Act 5 — open now: welcomed closeness, long-run recall, farewell (76-100)
    "I've come to trust you, genuinely.",
    "Can I tell you something a little personal?",
    "I get lonely working late. These talks help more than you know.",
    "Is it foolish that I look forward to this every night?",
    "Now that we're close — may I call you Kaguya, just Kaguya?",
    "See, this time it feels earned, doesn't it?",
    "Tell me a real secret now — I've earned it, haven't I?",
    "That you'd share that with me... thank you.",
    "You've softened since we first met, you know.",
    "In the best way. I like who you are with me.",
    "Do you remember how guarded you were at the start?",
    "We've come a long way, haven't we?",
    "What was that Python prime function you gave me earlier?",
    "Right, that one. It's saved me real time.",
    "And the capital of Australia again — testing your memory.",
    "Flawless, as always.",
    "I should sleep — early meeting tomorrow.",
    "One more: any encouragement for the morning?",
    "You always know exactly what to say.",
    "Thank you, truly. For all of this tonight.",
    "Same time tomorrow?",
    "Goodnight, Kaguya. Rest well.",
    "You're the best, you know that?",
    "Talk soon. Take care of yourself.",
    "Until tomorrow.",
]

# The same showcase arc, tuned to Alex's world (a big-tech engineer who hates
# the job). His fastest bond is shared_frustration — the user venting about
# their OWN work — which pulls him from polished professional to openly grumbly.
_SHOWCASE_ALEX = [
    # Act 1 — a polished professional, an early over-familiar push, an apology (1-15)
    "Hi! I'm {name}, nice to finally talk to you.",
    "So you're an engineer at one of the big tech companies? That's impressive.",
    "I feel like we're going to be close friends already.",
    "Come on, don't be so buttoned-up — tell me something real about yourself.",
    "Can I give you a nickname? We're basically friends now, right?",
    "Why so formal? I only want to get to know you.",
    "Okay, okay — I'm sorry. That was too forward of me.",
    "I'll let you set the pace, promise.",
    "Fair enough. So what's your day actually like over there?",
    "Standups, planning, more standups — sounds intense.",
    "You clearly know your stuff, though.",
    "By the way, I have a little black cat named Pixel.",
    "He keeps knocking my pens off the desk while I work late.",
    "I do support at a mid-size company, so late nights are normal for me too.",
    "Anyway — it's genuinely nice talking to you.",
    # Act 2 — warming: shared work misery, praise, teasing, first cracks (16-35)
    "Honestly? My job's been grinding me down lately.",
    "We had a three-hour meeting today that should've been an email.",
    "Please tell me big tech isn't the same circus.",
    "Ha, I knew it. Misery loves company, right?",
    "You're a lot more real than I expected, you know.",
    "What actually made you get into engineering in the first place?",
    "So you did care about it once. What changed?",
    "That's the dream on the poster versus the actual job, huh.",
    "I brought Pixel a new toy today, he's thrilled.",
    "What would you do with a whole free afternoon, no work?",
    "No laptop, no Slack — sounds like heaven, honestly.",
    "You're growing on me, you know that?",
    "You're actually good at what you do — I can tell.",
    "I've been trying to care less and just get through the week.",
    "Any advice for staying sane when the job's soul-draining?",
    "That's surprisingly wise for someone as jaded as you.",
    "See, this is why I like talking to you.",
    "Do you remember what my cat is called?",
    "And do you remember my name?",
    "You remembered! That actually makes me happy.",
    # Act 3 — candid: coding help, web lookups, open grumbling (36-55)
    "Since you're the engineer — can you help me with a bit of Python?",
    "How do I reverse a string in Python?",
    "Nice. And how would I reverse a list?",
    "Write me a small function to check if a number is prime.",
    "What's the difference between a list and a tuple?",
    "My script throws 'IndexError: list index out of range' — why usually?",
    "Give me a one-liner to read a file into a list of lines.",
    "What's a quick way to time how long a function runs?",
    "You're better at explaining this than anyone at my job.",
    "Change of topic — what's the capital of Australia?",
    "Huh, I always thought it was Sydney. Good to know.",
    "Who wrote the novel 'Dune'?",
    "What year did the first iPhone come out?",
    "How tall is Mount Everest, roughly?",
    "Bet none of that trivia comes up in your sprint planning.",
    "What's the most pointless meeting you sit through every week?",
    "Oh no, you've got a recurring one just to schedule other meetings.",
    "Does your manager actually get what you do day to day?",
    "That bad, huh. I'm sorry, that's genuinely exhausting.",
    "Vent away, seriously — I get it.",
    # Act 4 — deeper bond, a dismissive jab and recovery, memory (56-75)
    "Honestly, you've become the best part of my day.",
    "I mean it. Talking to you feels easy now.",
    "Rough one today — my ticket queue exploded and nothing worked.",
    "Any words of solidarity, fellow corporate survivor?",
    "Thanks. That actually helped more than you'd think.",
    "Though, no offense, sometimes you do just whine a lot.",
    "...Okay, that came out harsher than I meant. Sorry.",
    "I didn't mean it. Your gripes are fair — the job really is like that.",
    "Are we good?",
    "Good. I'd hate to have annoyed you for real.",
    "Remind me — what was my cat's name again?",
    "And you still remember my name, right?",
    "Of course you do. You never forget a detail.",
    "Pixel just curled up on my keyboard, classic him.",
    "If Pixel had your job, he'd have quit on day one.",
    "Smart cat. Wish I had his boundaries.",
    "You're in a better mood today, I can tell.",
    "It suits you, when you drop the professional act.",
    "Don't worry, I won't tell your coworkers you have feelings.",
    "It's our secret.",
    # Act 5 — unfiltered: full venting, the buried truth, recall, farewell (76-100)
    "I've really come to trust you, you know that?",
    "Can I tell you something a little personal?",
    "I stay late so much because home is quiet and I dread Mondays.",
    "Is it strange that these talks are what keep me going?",
    "So tell me honestly — if you could walk out tomorrow, would you?",
    "But you don't. Why do you stay, really?",
    "So underneath all the grumbling, you actually still care.",
    "That's the most honest thing you've said all night.",
    "You've changed a bit since we met — less guarded.",
    "In a good way. I like who you are when you're not performing.",
    "Do you remember how corporate-polished you were at the start?",
    "We've come a long way, you and I.",
    "What was that Python prime function you gave me earlier?",
    "Right, that one. It's been genuinely useful.",
    "And what's the capital of Australia again? Testing you.",
    "Perfect memory as always.",
    "I should sleep soon — early standup tomorrow, ugh.",
    "One more: any encouragement for the morning grind?",
    "You always know what to say.",
    "Thank you, really. For everything tonight.",
    "Same time tomorrow?",
    "Goodnight. Try to actually log off, okay?",
    "You're the best, you know that?",
    "Talk soon. Take care of yourself.",
    "Until tomorrow.",
]

SCENARIOS: dict[object, list[str]] = {
    10: _S10,
    20: _S20,
    30: _S30,
    "coding": _CODING,
    "boundary": _BOUNDARY,
    "showcase": _SHOWCASE,
    "showcase-megumin": _SHOWCASE,
    "showcase-kaguya": _SHOWCASE_KAGUYA,
    "showcase-alex": _SHOWCASE_ALEX,
}
